### ISSUE TITLE
跑着跑着崩溃了 

### ISSUE THREAD

**Issue by zhongmichael** [xujiaji/DMView2#11]
03-28 12:23:36.035 29783-29830/com.xujiaji.dmview2 A/libc: Invalid address 0x7d47687580 passed to free: value not allocated
03-28 12:23:36.036 29783-29830/com.xujiaji.dmview2 A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 29830 (pool-3-thread-4)

**Comment by xujiaji** [comment]
额... 提示的错误堆栈信息有吗？这个看不懂具体啥意思

**Comment by dujingxue1997** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.Comparable.compareTo(java.lang.Object)' on a null object reference
        at java.util.PriorityQueue.siftDownComparable(PriorityQueue.java:703)
        at java.util.PriorityQueue.siftDown(PriorityQueue.java:689)
        at java.util.PriorityQueue.removeAt(PriorityQueue.java:621)
        at java.util.PriorityQueue.remove(PriorityQueue.java:378)
        at com.xujiaji.dmlib2.widget.Controller.addToDisplay(Controller.java:348)
        at com.xujiaji.dmlib2.widget.Controller.addDMInQueue(Controller.java:312)
        at com.xujiaji.dmlib2.widget.Controller.runTask(Controller.java:115)
        at com.xujiaji.dmlib2.widget.Controller.run(Controller.java:102)
        at java.lang.Thread.run(Thread.java:764)

**Comment by dujingxue1997** [comment]
跑着跑着就崩溃了，   mNewDMQueue.remove(entity); 这行报错
